
[[information_wants_to_be_valuable]]
== Information Wants to be Valuable

_May 2001_

_Originally written for a Nature magazine series on the impact of the Web on publishing, and still available at www.nature.com/nature/debates/e-access/index.html. I argue that the particulars of the publisher’s role certainly change when works are published online, but the value of their work to both authors and readers remains constant._

“Information doesn’t want to be free. Information wants to be valuable.” I first heard this gem from Larry Wall, creator of the Perl programming language. Like many other open source software authors, from Linus Torvalds, creator of Linux®, to Tim Berners-Lee and his spiritual descendants at the Apache web server project, Larry discovered that one way to make his information (i.e., his software) more valuable was to make it free. Larry was thus able to increase its utility not only for himself (because others who took it up made changes and enhancements that he could use), but for everyone else who uses it, because as software becomes more ubiquitous it can be taken for granted as a foundation for further work. The Internet (based on freely available software including TCP/IP, BIND, Apache, _sendmail,_ and so on) demonstrates clearly just how much value can be created by the distribution of freely available software.

Nonetheless, it is also clear that others, Bill Gates being the paramount example, have found that the best way to make their information valuable is to restrict access to it. No one can question that Microsoft has created enormous value for itself and its shareholders, and even its critics should admit that Microsoft has been a key enabler of the ubiquitous personal computing on which so much of our modern business world depends.

What many people fail to realize is that both Larry Wall and Bill Gates have a great deal in common: as the creators (albeit with a host of co-contributors) of a body of intellectual work, they have made strategic decisions about how best to maximize its value. History has proven that each of their strategies can work. The question, then, is one of goals, and of the strategies to reach those goals. The question for publishers and other middlemen who are not themselves the creators of the content they distribute, is how best to serve those goals. Information wants to be valuable. Publishers must focus on increasing the value, both to its producers and to its consumers, of the information they aggregate and distribute.

I am neither a practicing scientist nor a publisher of scientific journals, but as a book and web publisher who works on a regular basis to document widely available “infrastructure” software (both free and commercial), I am daily confronted with decisions akin to those reflected in the debate now being carried in these pages. Because I publish books about free software, the people best qualified to write about it are often the authors of the software. Like scientists, those authors often have as their ideal the widest possible dissemination of their software and information about how to use it, rather than the greatest economic gain. They would like to see the documentation they write distributed freely along with the software.

At other times, though, software authors see documentation as an afterthought. They would rather not deal with it, and hope that someone else will. In those cases, the question of compensation often comes into play. Will a third party who is motivated chiefly by money earn enough from this book to justify the time writing it?

In helping authors to navigate this discussion, I try to bring them back to their goal. Is it maximum dissemination of information or is it earning enough to justify the work? I should note that the jury is still out on whether making the text of a book freely available helps or hurts sales of a print book. There is evidence on both sides.

In some cases, such as Eric Raymonds book, _The Cathedral &amp; The Bazaar,_ free distribution of the content created the “buzz” that allowed us to publish the same material successfully in print. In other cases, such as our initial publication of the _Linux Network Administrator’s Guide,_ sales were reduced because other companies republished some or all of the book at lower cost, which they could do because they had no development costs or royalties. However, over time this problem abated, because the fact that those publishers were not adding value was recognized by the target audience, and eventually marginalized their products.

I see many parallels between the work of free software authors and the work of scientists. In most cases, both are more interested in making sure their work is disseminated than in maximizing their return from it. In most cases, the target reader is a peer of the author. Publishing is designed to enhance reputation as well as to spread the word. Publishers must be careful to keep prices fair, lest they be seen as taking advantage of the goodwill of their authors, gouging the very customers who also produce their content.

In this kind of environment, you have to ask about the role of the publisher as middleman. No one who started as a self-published author and gradually developed all the infrastructure of publishing (as I did) can question the enormous added value that a publisher brings to the table. This value includes editing (which starts with content filtering—the choice of what to publish and what to refuse—and extends through content development and quality control), manufacturing of the physical product, marketing, sales, distribution, and collecting and disbursing money.

In the early days of the World Wide Web, the rhetoric was that anyone could be a publisher. After all, with cheap, ubiquitous web servers, the cost of printing and inventory was minimized. There was a great deal of talk of “disintermediation.”

In a few short years, the reality has turned out otherwise. It is quite easy to put up a web page, not so easy to discover it. The fundamental job of publishing is precisely mediation: mediation between a huge class of potential authors, and an even larger class of potential readers. Simple mathematics dictates the rise of multi-tiered distribution chains, in which publishers aggregate authors, various types of resellers aggregate readers, and wholesalers aggregate publishers for resellers and resellers for publishers. The same multi-tiered distribution has emerged on the Web. Betting on this logic, my company created the first Web portal, a site called GNN (Global Network Navigator) in early 1993. We sold the site to AOL in 1995, and they later folded it into their main service, but the vision of web aggregators (i.e., publishers) has unfolded pretty much as I imagined it.

Many people with their own web pages end up writing for better-established web sites; those sites are further aggregated for readers by search engines, directories, and other portals such as Google, Yahoo! or AOL. In fact, web publishers now employ full-time workers to ensure that their pages are listed on these gateway sites, much as publishers of printed books employ sales people. A large proportion of Internet advertising has come from web sites trying to get better visibility for their product.

However, the Web does bring another wrinkle: the ability of groups to self-aggregate. The core functions of publishing, from content filtering to audience aggregation, can be performed by a group of interested users. This is particularly true when there is already a well-defined target community. This can be a disruptive force in the publishing marketplace. So, for example, sites such as Cnet and ZDnet spent tens of millions of dollars building and promoting portals for technical information on the Web, while two college students built a site called Slashdot (“News for Nerds. Stuff that matters.”) into a similarly powerful market presence simply by inviting their readers to submit, organize, and comment on their own content.

Interestingly enough, though, as Slashdot has grown in popularity and evolved into a real business, it has needed to add more editorial staff to filter the submissions of a growing marketplace of readers who now recognize that exposure via Slashdot is a powerful marketing tool. In short, even a community-centric effort ends up recreating some of the fundamental dynamics of publisher as middleman and aggregator.

What this evolution illustrates is that publishers will not go away, but that they cannot be complacent. Publishers must serve the values of both authors and readers. If they try to enforce an artificial scarcity, charge prices that are too high or otherwise violate the norms of their target community, they will encourage that community to self-organize, or new competitors will emerge who are better attuned to the values of the community.

