
[[beyond_the_book]]
== Beyond the Book

_April 2000_

_At the 2000 Waterside Publishing Conference, I was invited to speak on a panel called “Beyond the Book.” The conference is aimed at an audience of computer book authors, editors, and publishers. The organizers were no doubt expecting a few words on what O’Reilly Media is doing with eBooks, with the online sites we publish, like xml.com, and with our technical conferences. But instead, what I spoke about was why O’Reilly has always reached beyond the book in all of our publishing efforts. This article is a summary of what I tried to say._

Most publishers think that their business is to create products that people want, and that accordingly transfer dollars from consumers’ pockets to their own. At O’Reilly, we believe that the core of our business is to transfer knowledge from people who have it to people who need it. Yes, we are in business to make money, but this is a kind of housekeeping, not the purpose of the business.

I like to compare business (or life for that matter) to an extended road trip. Say you want to travel America by the back roads. You need gas for your car, food and water for your body Especially before heading across Death Valley or the Utah salt flats, you’d better be darn sure that you have enough gas in your tank. But you certainly don’t think of your trip as a tour of gas stations! What’s the real purpose behind what you do?

Why then do so many companies think that they are just in the business of making money? At O’Reilly, our products aren’t just books, conferences, and web sites: they are tools for conveying critical information to people who are changing the world. Our product is also the lives of the people who work for us, the customers who are changed as a result of interacting with us, and all the “downstream effects” of what we do.

When I started the company, my stated business goal was a simple one: “Interesting work for interesting people.” Above all, we wanted to be _useful._ Our financial goals were just to keep afloat while doing something worthwhile.

We started our business life as a technical writing consulting company. Between paying jobs, we thought we could perhaps create some value by documenting Unix programs that didn’t have a manual. We wrote books like _Learning the vi Editor, sed &amp; awk,_ and _UNIX in a Nutshell_ not because we thought there was a huge market waiting to be tapped, but because we used these programs, had learned about them, and thought we might as well put our skills to use passing on what we knew.

Our first print runs for the earliest of these books were only a few hundred copies. No other publisher touched these topics because they thought the market was too small. We didn’t know enough to have such an opinion. All we knew was that people were using this software, and there wasn’t much good documentation. And because we thought the subject matter was important, we kept promoting the books, rather than dropping them and going on to look for greener pastures. As it turned out, each of the books I mentioned went on to sell hundreds of thousands of copies.

Once we realized the possibilities for financial success in publishing, we tried not to forget our roots. Instead of pursuing the “hot” topics of the day, we kept trying to document software that we found interesting and useful. One of those things was the Internet, which was just emerging from academia into wider use. Our book, _The Whole Internet User’s Guide &amp; Catalog,_ published in 1992, ended up having profound impact. It sold over a million copies, introduced many people to the Internet for the first time, and was a key factor in the explosive growth of the early commercial Internet.

One of the topics we covered in that book was the World Wide Web. We didn’t choose to cover the Web because our marketing department told us there was great demand for information about it! There wasn’t. At the time we published the book, there was a total of 200 web sites. But we knew the Web was an important technology and we wanted to spread the word. Once again, simply trying to do something worthwhile was the cornerstone of a great success.

It was at this time that we stumbled on an incredibly powerful approach to marketing. We had recently hired Brian Erwin, the former director of activism for the Sierra Club, to head our PR efforts. Brian helped us to realize that we shouldn’t be promoting our products. He showed us how much more powerful it was to talk about the technologies themselves, the possibilities that they might unleash, or the threats to the future that we might encounter. He reminded us that in marketing, as well as in product development, the best way to have an impact was to be useful.

We sent copies of _The Whole Internet User’s Guide_ to every member of Congress, and launched a massive PR campaign about the Internet. We’ll never know how much impact our evangelization of the Net, and most particularly the World Wide Web, really had. After all, as they say, success has a thousand fathers. But we’ve heard, for example, that the NCSA team that developed the Mosaic web browser (predecessor to Netscape Navigator®) first learned of the Web from an O’Reilly direct mail piece. We also created the first web portal, a site called GNN (Global Network Navigator). GNN was the first advertising-supported web site (started in early 1993), and was a prototype for sites such as Yahoo!, HotWired, and many other early web sites. While GNN vanished into oblivion after we sold it to AOL in 1995, its influence on the early Web was immeasurable.

In those early years of the Web, there weren’t any venture capitalists looking for the big win. We invested millions of our own dollars in GNN, despite being a very small company at the time, and spent a lot of time trying to persuade big publishing companies that the Web was going to be important. Their narrow, bottom-line focus made them miss the biggest opportunity in any of their lifetimes. Those opportunities went to newcomers.

Our next big success was with what is now called open source software. We had published a book called _Programming Perl_ in 1991. At the time, Perl was an obscure programming language with an enthusiastic following among Unix system administrators. As the Web took off, it became the dominant language for building dynamic web sites. Sales of the book exploded, and the second edition was one of the most successful computer books of 1996.

But something bothered me. Despite the evidence of its importance, Perl got virtually no notice in computer trade publications. There was no marketing budget, no PR agency, and so the press ignored Perl despite its grassroots success. We decided to spread the word. We organized a Perl Conference in 1997 not because we realized what a huge opportunity the technical conference business would turn out to be for us, but because we felt that the Perl language and the Perl community needed a voice, and a place to gather.

The success of the first Perl Conference got me thinking, and the more I thought about it, the more I realized that there were many technologies, like Perl, that were created as “free software,” but which didn’t get noticed by the mainstream. I knew from the success of the books like _DNS and Bind, Apache: The Definitive Guide, sendmail,_ and _Running Linux_ that they covered important technologies. What’s more, these technologies had something unusual in common: they had all been developed not by commercial vendors, but by an idealistic network of independent developers.

I decided to organize a “summit meeting” of key free software developers, including Linus Torvalds (the Linux kernel), Larry Wall (Perl), Brian Behlendorf (a cofounder of the Apache group), Paul Vixie (BIND—the software behind the Internet’s domain name system), Eric Allman (_sendmail,_ the Internet’s dominant email server), plus Eric Raymond, whose groundbreaking paper “The Cathedral &amp; The Bazaar” had inspired Netscape to commit to releasing the source code for its next generation of web browsing software. The meeting also included people associated with the FreeBSD operating system and the Free Software Foundation’s GNU project.

It was at that summit that the group formally decided to endorse the term “open source software” instead of “free software,” which had negative connotations for corporate America. But most importantly, we were able to get across a story to the press, that much of the software behind the Internet, as well as the emergent Linux operating system, had come from an unrecognized wellspring of creativity, from people who were solving problems not for commercial gain, but because they loved what they were doing. These people wrote software to solve their own problems; they gave it away because they thought it might be useful to someone else. Their brilliance and their generosity was changing the world.

Most of you know what has followed. Within a few months, Linus Torvalds was on the cover of _Forbes,_ with Larry Wall, Brian Behlendorf, and the Free Software Foundation’s Richard Stallman featured inside. Linux has taken off. And the idea, which seemed so novel at the time, that the Internet was built on open source software, that programs like Apache, Perl, MySQL, BIND, and _sendmail,_ are important far out of proportion to their nonexistent marketing budgets, is now widespread. And of course, sales of O’Reilly’s books on these topics have soared. Once again, we’d scored a marketing coup not by promoting our products, but by promoting big ideas.

My recent well-publicized tussle with Amazon.com over their 1-Click and Associates patents springs from the same roots. I worried that publically taking my biggest reseller to task might hurt my business, but it had become clear to me that the importance of the issue outweighed considerations of profit and loss. As it turns out, my efforts have strengthened the relationship between O’Reilly and Amazon.com, and Jeff Bezos has joined me in my campaign for reform of the software patent system.

In short, O’Reilly has become one of the pre-eminent computer book publishers not by “following the money,” but by following the trail of value. We publish books about topics that seem important, and they succeed because they fill a real need. We base our marketing and PR campaigns not on flash, but on substance.

A similar approach to thinking “beyond the book” is behind our other publishing ventures. I was once asked by an investment banker why my brother James and I had started Travelers’ Tales, when the travel book market is so much less lucrative than the computer book market. We did it because we saw a problem: tourism is becoming the world’s largest industry It can be a soulless industry, one that treats the world as a theme park, with a list of attractions to be sampled, or it can be a thoughtful one that celebrates differences and rewards attention to the inner life of the traveler.

Travelers’ Tales has won over 50 awards, including (three times) best travel book of the year from the Society of American Travel Writers. Like many O’Reilly efforts, it’s also spawned a host of imitation series from other publishers. It’s a thriving publishing company whose sales are growing at 20% a year. But that’s not what we’re about. We’re about changing the world, helping people get more out of their travels, and destinations more out of their visitors.

Why did we go into consumer health publishing? Because where is there greater “information pain” than when someone is hit with a life-threatening disease? Our Patient Centered Guides provide information from “health system hackers”—patient advocates who have experienced the best and worst of what the medical system has to offer, and who want to pass along their experience for sufferers of chronic or life-changing diseases. We’re not just in this business to make a dollar; we’re in it to make the world a better place. We look to make money so we can do more of what’s important.

But my point isn’t to brag about O’Reilly’s accomplishments in publishing or beyond it, though I am certainly proud of them. I am trying instead to urge each of you to think yourselves beyond the book. I want you to think why the technologies you cover are important, and how you can help to tell their story. Focus on making a difference, not on making a dollar, and I’ll lay odds you’ll make both.

Publishing is part of a noble tradition. It was born out of the same wellsprings as our great university system, out of the spirit of inquiry that brought us modern science. As authors, editors, and publishers, you are not just cogs in a money machine. You are scribes, capturing knowledge that might otherwise be lost; you are teachers, passing on knowledge that might otherwise go unheeded.

In short, I am here to tell you that what exists beyond the book is a world where you can make a difference.

