
[[buy_where_you_shop]]
== Buy Where You Shop

_May 2003_

_Most issues aren’t black-and-white, though it’s often easier to fall into thinking of them in that way than to wrestle with subtleties and consequences. In this piece, written for one of our catalogs, I make the case that value is more than price, and that it’s in our self-interest to support what we value._

Like all technology revolutions, the Internet is profoundly disruptive. For all its promise, it can destroy old ways of life before we realize the value of what we’re losing. Part of the process of integrating new technology is developing social norms for its proper use. We have much to learn about how to use the Internet properly—how to avoid abuses such as spam, invasions of privacy, attempts by large corporations to control how we use technology, and the like. But there’s also a more humble area of disruption that I’d like to bring to your attention. Let me start with a story.

A few months ago, I was talking with one of my most loyal retail customers, a specialty computer bookstore in Massachusetts. “We survived the chains, and we survived Amazon,” he said, “but I don’t know if we’re going to survive the online discounters. People come in here all the time, browse through the books on display, and then tell me as they leave that they can get a better price online.”

Now, you might say, as the Hawaiian proverb notes, no one promised us tomorrow. Businesses, like individuals and species, must adapt or die. And if the Internet is bad for small, local retailers, it’s good for the online resellers and it’s good for customers, right?

But think a little more deeply, and you realize that my friend wasn’t complaining that people were buying books elsewhere. He was complaining that people were taking a service from him—browsing the books in his store—and then buying elsewhere. There’s a world of difference between those two statements. Online shopping is terrific: you can get detailed product information, recommendations from other customers, make a choice, and have the product delivered right to your door. But if you aren’t satisfied with the online shopping experience, you want to look at the physical product, for example browsing through a book in the store, you owe it to the retailer—and to yourself—to buy it there, rather than going home and saving a few dollars by ordering it online.

Think about it for a minute: the retailer pays rent, orders and stocks the product, pays salespeople. You take advantage of all those services, and then give your money to someone else who can give you a better price because they don’t incur the cost of those services you just used. Not only is this unfair; it’s shortsighted, because it will only be so long before that retailer closes his or her doors, and you can no longer make use of those services you enjoy.

If you like shopping in bookstores, remember this: many independent booksellers are on the ropes. (One store owner we know resorts to ordering books on personal credit cards when she is put on credit hold by publishers because she can’t pay her bills.) Even in the chains, computer book sections are in danger of shrinking in favor of other sections where sales are more robust. If you value the bookstore experience, my advice is this: buy where you shop. I buy lots of books online. I read about them on a blog or a mailing list, and buy with one click. But when I shop for books in bookstores, I buy them there, and so should you. Don’t just look for the best price. Look for the best value. And if that value, for you, includes the ability to page through a book, support your local bookseller.

This story is the tip of an iceberg, of course. As with the unintended consequences of previous revolutions (pollution from automobiles and industrialization, for instance), it takes a strenuous forethought to make sure we don’t inadvertently damage parts of our world that we take for granted. It’s easy to get fired up about large technical, social, and political issues, but the future we create is even more the result of small decisions we make every day.

