
[[fishing_with_strawberries]]
== Fishing with Strawberries

_A brief article I wrote for O’Reilly’s internal company newsletter in early 1995._

Recently, several of us were talking with an investment banker with whom we’ve been having some exploratory talks about finding strategic partners that want to figure out how to play this new Internet game.

The investment banker made a statement that really struck me, and the more I thought about it, the more I saw in it, both to agree and disagree with.

The statement was this: “You don’t fish with strawberries. Even if that’s what _you_ like, fish like worms, so that’s what you use.”

He was referring specifically to finding out what the real needs of the potential strategic partners might be, since they might be focussing on something other than what we think is most important about what we have to offer.

That’s really good advice for any sales situation: understand the customer and his or her needs, and make sure that you’re answering those needs. No one could argue with such sound, commonsense advice.

At the same time, a small voice within me said with a mixture of dismay, wonder, and dawning delight: “But that’s just what we’ve always done: gone fishing with strawberries. We’ve made a business by offering our customers what we ourselves want. And it’s worked!”

On one level, the difference between the two points of view is simply the difference between selling one on one to a very targeted prospect and selling to a mass market, where you are casting a wide net, and some set of potential customers will match your own “strawberry” profile.

But there’s perhaps a deeper level on which this difference is one on which a great deal that is special about this company hinges. We seek to find what is true in ourselves, and use it to resonate with whatever subject we explore, trusting that resonance to lead us to kindred spirits out in the world, and them to us.

I like to think that we have the capability to fish with worms when necessary, but that in general, we’re farmers, not fishermen, and strawberries go over just fine.

