
[[some_necessary_qualities]]
== Some Necessary Qualities

_I wrote this for our in-house newsletter in December, 1993, as I realized that we were starting to move from a company in which everyone knew each other and culture was based on personal relationships to one in which our values needed to be institutionalized._

As we approach the end of 1993, we’re possibly facing a greater rate of change than we did when we first came to publishing in 1985, or when I moved half the company to California in 1989.

With so much happening, we need all the best in ourselves that we’ve brought to the business so far, plus a lot of new strengths as well.

Creativity . . . Well, some people might say we perhaps have too much of that, and need to add a pinch more restraint. But in times when new projects seem to be bursting out of every corner, creativity may serve not just to start more things to overwhelm us, but instead to guide us in the next level of integration. The last thing we want to do is to rigidify in order to contain and manage the genies we’ve unleashed. We simply need to turn our creativity to new purposes.

Courage . . . We’ve broken a lot of comfortable molds in the last year. For example, we’ve broken out of the familiar X/Unix market where we’re well known and well thought of for a much wider market where we can no longer assume that customers know very much about us. This puts us back in a position where we have to really reach out to sell, and can’t just sit back and wait for people to come to us. This can be uncomfortable—it’s a different level of cold calling—but is essential for a business that’s growing and not just resting on its laurels. Each of us who has customer contact now has to carry the whole message of the company and what it’s about, rather than just coasting on what everybody already knows about us.

Curiosity ... To me, this has always been the foundation of the company’s strength, the quality that makes us look for interesting projects rather than just ones that we are already convinced will be successful. The desire to learn new things and solve new problems and then to share what we’ve learned has got to remain at the top of our list.

Kindness and caring . . . What do they have to do with business? Everything! Especially as the pace and the pressure pick up, we have to keep on trying to be good to each other, to our suppliers, and to our customers. What good does it do us to be successful by all the usual business indicators if what we are creating is unhappiness?

Foresight and good judgement ... I think that we’ve always had a certain kind of strategic thinking that’s helped us to pick good markets and topics, and to be in the right place at the right time. However, we need to find out how to apply our vision to ourselves and not just to the outside world. What kind of organization do we need to have to grow into our next stage?

I could go on and list all the usual virtues, because after all, the same things that make the foundation of a good life make the foundation of a good business.

Still, there are specific challenges, and the biggest one is how to institutionalize the qualities that have up to now been carried for the organization by us as individuals. Especially as the pace of growth picks up, it’s increasingly easy for a company to be defined solely by its commercial goals.

It’s becoming clear that the company is going to keep growing, and to be around for many years to come. If that’s the case, one of our major challenges is to find a way to build company structures that support our underlying goals and values, to create a truly moral organization that is as effective as it is good, and will stay that way a hundred years from now, when all of us are gone.

