
[[knowing_when_to_let_go]]
== Knowing When to Let Go

_A piece I wrote for our internal company newsletter in November of 1992, in response to mounting stress at the company as we became more and more successful._

As I hear mounting tales of overwhelm—too much to do, too many things going right—from customer service, from marketing, from production, from editorial, (from my own psyche!), I am impelled to give a bit of contrarian advice.

When you feel yourself starting to clutch, to worry that you can’t keep up, let go! There are times when the conscious mind can’t keep up, but the unconscious will do just fine. The faltering steps of a newcomer to a dance become assured to the extent that she is able to forget the individual steps and yield to the music. The straining load of an engine getting up to speed gives way to a smooth hum as it slides into gear. I seem to remember (or did I make this up?) a wonderful martial arts book or movie in which an old master “bumbles” his way through a room, accidentally disposing of each of his highly trained opponents with strokes that might be luck but are more likely the highest level of skill guided by complete reliance on intuition. What I’m saying is meant in no way to diminish the huge increase in workload many of us are facing as a result of the company’s success. This is perhaps most striking in customer service, where they went from about 3800 orders in September to nearly 7200 in October—very close to a doubling of die normal workload. Such increases require urgent practical steps to keep things from going haywire.

Nonetheless, I’ll stick to my point: the conscious mind sometimes gets in the way, worrying about how to fit everything in. Periodically, I find myself about to explode, as I reach some kind of inner limit to how many things I can keep track of. If I’m lucky, a certain kind of letting go, a certain kind of surrender or forgetting what I know (and remembering the power of what I don’t know!) blasts it all into insignificance.

I find myself somehow deciding that I can’t keep up, and trusting my unconscious (or the hidden power of my spirit) to help me find my priorities. And often, I find that as soon as I do let go in this way, I find myself powering through the same tasks that before seemed insurmountable.

An old friend of mine used to refer to this as “jet” vs. “piston” functioning. A piston engine is overloaded at speeds that are hardly enough to engage a jet.

I also find that sometimes some of the things I was worrying about just aren’t that important. In that _Rules of Thumb_ handbook I keep promising to finish, I quote a wonderful passage from Lao Tzu. He’s cataloging some of the qualities that are attributed to a wise man, and adds:

_And this one also:’Roiled as a torrent’_

_Why roiled as a torrent?_

_Because when a man is in turmoil how shall he find peace_

_Save by staying patient till the stream clears?_

_How can a man’s life keep its course_

_If he will not let it flow?_

What I’m trying to say here is that we don’t need always to be in control, but rather, to be good at responding to change, to have the wisdom to know when to act, and when to wait “till the stream clears.”

I know that this article is already burdened with analogies, but let me close with one more. When bodysurfing (and in many other sports), you succeed by harmonizing yourself with forces that are more powerful than you are, rather than by trying to force them to your will. That’s the kind of attitude I’m trying to urge on you now—not passivity, but rather an active surrender that finds the exact right moment and the center of the wave.

