
[[walking_the_kerry_way]]
== Walking the Kerry Way

_My contribution to_ Travelers’ Tales Ireland, _published in March, 2000._

I hadn’t spent much time with my brother Frank since he was about twelve years old, back in 1973. That was the year I’d gotten engaged to a non-Catholic, and my parents wouldn’t let me bring her home because “it would scandalize the children.” I was nineteen and equally sure of myself, so I refused to come home without her.

I finally gave in seven years later, when my father’s health was failing, and went home for a visit alone. After that, my parents also relented, and met my wife and three-year-old daughter for the first time. Our mutual stubbornness had cost us precious time together as a family, a loss made especially poignant by my father’s death six months later.

My relationship with my younger brother and sisters took years to recover. By the time I came home after my long exile, Frank was away at college, and thereafter we’d met mainly at family holidays and reunions. Still, we’d found many common interests and a mutual admiration. Both of us were entrepreneurs—I in publishing, he in construction—and both of us had struggled with how to build a business with a heart, a business that served its employees as well as its customers. In many ways, our lives were mirror images, seven years apart.

But there was one big crack in the mirror, one gulf between us that we skirted politely (most of the time): while I had long ago left the church, Frank remained a committed Catholic. He had also retained an abiding love for Ireland, to which he had returned again and again with my father, mother, and sisters in the years when I was _persona non grata._ He and my father had gone for many a tramp around Killarney, the town where my father was born, and where my aunt still lives. Mangerton, Tore, and the McGillicuddy Reeks were more than names to Frank; hikes on the slopes of these mountains were the source of the richest memories of his childhood and young adulthood.

I envied Frank the time he’d spent in Ireland with my father, and I’d always wanted to spend more time there myself. When my’mother suggested that Frank and I might want to walk part of the Kerry Way together (a higher altitude walking version of the Ring of Kerry), we both jumped at the chance. I had a week between a talk I was due to give in Rome and another in London. It was March—not the best time to visit Ireland—but Frank could get free, and with his eighth child on the way, it was now or never.

We set out from Killarney on a blustery day Though neither of us had done much recent hiking, we had an ambitious itinerary, about eighteen miles a day for the next five days. We were planning on staying each night at bed &amp; breakfasts along the way, but we still carried packs with plenty of extra clothes.

The first day took us through Killarney National Park, up around the back of Tore, then down across the road to Moll’s Gap and into the Black Valley. The hike took more out of us than we expected, and we tottered the last few miles, grateful that our guest house was at the near end of “town” (a sprinkling of houses spread over the better part of a mile).

After a hearty dinner of local lamb chops, though, things began to look up, so when Frank confessed that it was his wife’s birthday, and that he wanted to go a mile up the road to the valleys only public phone, outside the youth hostel and the church, to call her, I agreed to go along. It was pitch dark by then, and raining to boot. We managed to stick to the road, though, and eventually came to the phone. Unfortunately, Angelique was not at home. How about going in to say a rosary for her, he asked?

Now, I hadn’t said the rosary for over twenty years, and wasn’t sure I even remembered how the “Hail Mary” went, but I agreed.

The church was open, of course, its outer door swinging in the wind. In Ireland, at least in the back country, the church is never closed. There was no electricity, and only a single candle burning by the altar. The wind howled outside, the door banged open and shut. We began to pray.

Frank helped me recall the words; the memories I’d never lost. When we were small, the rosary, even more than dinner (where my mother never sat down till everyone else had eaten), was the time the family was all together. As we droned aloud through the decades, the joyful, the glorious, and the sorrowful mysteries, I remembered my father’s passing.

He had had a heart attack. He knew himself to be a dead man, he said. He was met by Mary, St. Joseph, and surprisingly, the devil. He begged for more time to make his peace with his family, and his wish was granted. The doctors brought him back, and as he lay in the hospital, intubated and unable to speak, he was desperate to communicate with each of us, scrawling on a small white slate. He wanted to reply to my letter, he said.

I had written him a few weeks before, telling him that even though I had left the church, I had absorbed so much of him, his belief, his moral values, his desire to be good, and to do good. I didn’t want him to think he had failed. His short, so poignant reply, written on a slate and soon erased, but burned forever in my memory: “God forgive me, a sinner.” His apology for the long years we had not spent together: “I only wanted you to be with us in paradise.” The desire for togetherness in a world to come had become a wedge between us.

As he recovered over the next few days, he was a different man. He had always embodied for me so much of the stern, dogmatic side of Catholicism. Now, in the face of death, all that was stripped away, and the inner core of spirituality was revealed. His passion for his God was the heart of his life. How could I have never seen it before? So many of us build a shell around who we really are; our inner world is as untouchable as the heart of an oyster, till forces greater than we are pry us apart. Now, all was exposed. “I never showed you the face of Christ when you were small,” he told my brother James. Well, he showed it to us then. It’s as if he’d been turned inside out, and all the love and spiritual longing that had been hidden by his shyness and his formality were shining out like the sun.

Three weeks later, the time he had asked for was up. He had another attack, and this time he went for good.

We had taken him back to Ireland to bury him. It was a magical day, early April but beautiful as only a spring day in Ireland can be beautiful, a day of radiance stolen from the gloom. The funeral mass in the cathedral was concelebrated by thirty or forty priests: his two brothers, his childhood friends, and many others come to honor the life of one of Killarney’s dear sons now coming home for good. (He had himself studied for the priesthood before deciding to pursue family life instead; his brothers Frank and Seumas had become senior in two of Ireland’s great orders of priests, the Franciscans and the Columbans.)

He was buried in a Franciscan robe. He had long been a member of “the little order of Saint Francis,” a lay organization devoted to Franciscan ideals. We learned then of small penances he would do, like tying rough twine around his waist under his clothes. As if it were still the Middle Ages! I would have scoffed, but Id seen the light shining through him when impending death had pried all his coverings away.

Afterwards, the four sons, Sean, James, Frank, and I, walked behind the hearse up the main street of the town. As the funeral procession passed, those walking in the opposite direction turned and took “the three steps of mercy,” walking with the procession. The depths of Ireland’s Catholic legacy was never so clear as when a group of loutish youths, who might have been a street gang anywhere else, bowed their heads and turned to take the three steps with us.

As we turned up the road to Aghadoe cemetery, a breeze blew, and the blossoms fell from the trees onto the coffin. If it had been a movie, I would have laughed. It’s never that perfect! Except it was.

The cemetery, crowned with the ruins of a sixth century chapel, looks down on the lakes of Killarney. Ham-handed farmers (my father’s schoolmates) helped us carry the coffin over rough ground to the family plot. Normally, after the service, we would have all left, and “the lads” would have filled in the grave. But we wanted a last farewell, so we sent the lads on their way, and Sean, James, Frank, and I filled in the grave.

Now, twenty-five years later, I was back in Ireland. My tiredness fell away. I was at the heart of my father’s mystery, the place where he had turned his passionate heart to God, and the place where he had wrapped it round with rituals that had kept me from seeing its purity and its strength.

Somehow, Frank had seen through the ritual, had shared in it and sunk his roots to the same deep place. I was honored that he was opening the door for me as well. “Hail Mary, full of grace, the Lord is with thee ...”

There are a thousand ways to God. Let us all honor the ways that others have found.

The next few days we wore our legs off, as the paths became wilder. The worst of it was the aptly named Lack Road, which our guidebook insisted had been used to drive cattle to market “within living memory” We couldn’t see how you could drive a mountain goat herd across it now, as we picked our way down an impossibly steep slope. We understood why our aunt, who had worked in Kerry Mountain Rescue, had insisted we pack so many extra clothes. Turn an ankle out here, and you’re many hours from help, with changeable weather bringing freezing rain at any moment. At one point, the trail, which had us up to our knees in mud at many a point, vanished beneath ten feet of water, only to reappear tantalizingly on the other side, with no apparent way across. Ireland is a wilder country than many people realize.

On the fourth day, we came round the crest of a hill and saw the ocean spread out below us. Thirty or forty miles back the other way, we could see the gleaming lakes of Killarney, and amazingly enough, the green below Aghadoe. We could see many of the passes we’d picked our way through over the last few days, the miles that had lent soreness to our feet.

Along the way, we had talked through much of the old pain of the lost years, we’d shared dreams of the present and the future, but as we went on, we’d mostly fallen into a friendly silence. The old magic of Ireland was driving our reflections inward, recreating in us the unique Irish temper—passion and wildness and boggy depths alternating with conviviality, and ending up in quietness—a mirror of the landscape and the changing weather.

